### PR TITLE
Added icons for menu items and icon color for both light & dark theme

### PR DESCRIPTION
**Pull request by Himanshu40**

### CODE REVIEW

**Comment by drossberg** [comment]
In principle okay. However, how did you made up the colors? How are they based on the `$Color-Icon` ones(?)

**Comment by Himanshu40** [comment]
First I saw that the background color is violet in the light theme, so I thought to pick a color that will not look so much bright and not so much dim. According to that I used a color picker from google and tested 3 different colors which will suit both light and dark themes. Then after that, I chose the final color for files, views, and ray trace.

**Comment by drossberg** [comment]
I'm asking because the View and Raytrace colors look okay, but the File color is a bit too blue, not purple, or?

**Comment by Himanshu40** [comment]
iconColor
In dark theme, the violet color doesn't suit with background color.

**Comment by Himanshu40** [comment]
- A new look of file icons in light theme:
lightTheme

- A new look of file icons in dark theme:
darkTheme

**Comment by Himanshu40** [comment]
For now, I have only changed the menu bar of file items in both light and dark themes. Here is a look:

- In light theme:
lightTheme

- In dark theme:
darkTheme

**Comment by drossberg** [comment]
Where are the new icons from? Who created them? Was it you?

**Comment by drossberg** [comment]
> > Where are the new icons from? Who created them? Was it you?
> 
> I downloaded them from `icons8` which is free.

The download is free, but they have a complex license agreement which requires at least two links in the about window. And, they write something about "personal use" there.

**Comment by Himanshu40** [comment]
@drossberg Added Apache License 2.0. Is this the right way to apply Apache 2.0 License?

**Comment by drossberg** [comment]
Is it possible to use the LICENSE file in AboutWindow?

**Pull request merged**
