### PR TITLE
Revert back to use object name toolbarButton instead of new object names

### PR DESCRIPTION
**Pull request by Himanshu40**
Removed new object names from `QToolButton` and reverted back to use object name `toolbarButton` because its property is already set in `arbalest_simple.qss`

### CODE REVIEW

**Comment by drossberg** [comment]
The last commit doesn't look right. See, there are no absolute colors at all in this file. This is because they all depend on the theme (currently light or dark), and this is what you should use here.

In addition, why do you set border and padding for QToolButton? I would understand adding QToolButton in line 40 of this file, by why made you these changes?

**Comment by drossberg** [comment]
I tested your changes and saw that you should first understand the old behavior. In your last PR you unfortunately changed the object names. This was rashly. I wasn't aware of the importance of the object name too. The name refers to the `#toolbarButton` settings in arbalest_simple.qss. There, the hover behavior is defined.

**Comment by Himanshu40** [comment]
> 

Ahh.. Now I see why `toolbarButton` is used for setting object names so that style property can be applied. I didn't see that made my own object names without knowing the consequences and later adding my own hover and padding.

**Comment by drossberg** [comment]
I've to ask for one more: Please, adjust the title and description of this pull-request to what was really done.

**Pull request merged**
