### PR TITLE
Add unsaved changes feature

### PR DESCRIPTION
**Pull request by Himanshu40**
- Add `bool maybeSave(int documentId, bool *cancel = nullptr)` which checks if the document has any unsaved changes and returns a bool value if the user pressed `save`, `discard` or `cancel`.
- Add `bool modified;` so that it can modify itself to true and false if there are new changes to the document.
- Add `ConstDatabase` instead of `MemoryDatabase` to make sure the database is not modifiable while getting BRLCAD Object.
- Shift `getBRLCADObject()` inside `Document` class.

### CODE REVIEW

**Comment by drossberg** [comment]
What's the reasoning behind `objectPresent`/`isObject()`?

**Comment by Himanshu40** [comment]
> What's the reasoning behind `objectPresent`/`isObject()`?

I thought ray trace works if some objects are present in the document. So I created a variable `objectPresent` which will check if there are any objects in the document and `isObject()` will return bool value of `objectPresent`.

**Comment by drossberg** [comment]
The ray-trace doesn't need any objects in the database. For if a ray-trace makes sense, it would be more important to check, if an object was selected (```Select()``` and ```UnSelectAll()``` in ```OrthographicCamera). But, I don't recommend to put much effort in this. Ray-tracing an empty scene isn't a big issue.

**Comment by drossberg** [comment]
Hmm, I see there several issues:
* Document::getDatabase() still returns BRLCAD::MemoryDatabase*. This allows unnoticed changes to it. Therefore, it has to be changed to BRLCAD::ConstDatabase*. Of course, this will cause compilation errors, which have to be fixed.
* Document::modifyObjectNoSet() doesn't change the database. I.e., modified doesn't need to be set to true. However, if you solved the first issue, this function may be not necessary anymore.
* BTW, the Document has a lot of code for redrawing. Does Document::Add() need drawing code too?
* The "cancel" logic in MainWindow::maybeSave() is not the one we talked about.
* I don't recommend to change a single color in the message box. You don't know the users color scheme and how your blue color looks there.

**Comment by Himanshu40** [comment]
> Hmm, I see there several issues:
> 
> * Document::getDatabase() still returns BRLCAD::MemoryDatabase*. This allows unnoticed changes to it. Therefore, it has to be changed to BRLCAD::ConstDatabase*. Of course, this will cause compilation errors, which have to be fixed.
> * Document::modifyObjectNoSet() doesn't change the database. I.e., modified doesn't need to be set to true. However, if you solved the first issue, this function may be not necessary anymore.
> * BTW, the Document has a lot of code for redrawing. Does Document::Add() need drawing code too?
> * The "cancel" logic in MainWindow::maybeSave() is not the one we talked about.
> * I don't recommend to change a single color in the message box. You don't know the users color scheme and how your blue color looks there.

- Added `ConstDatabase` instead of `MemoryDatabase`
- Removed `Document::modifyObjectNoSet()`
- `modified` is set to `true` since `Add()` adds new primitive to the document.
- Removed color scheme for messagebox.

**Pull request merged**
